### ISSUE TITLE
Please add Karma

### ISSUE THREAD

**Issue by JohnnyQuazar** [Redmega/bitburner-save-editor#4]
I only ever hack my save to get over the karma requirement. Would be splendid to be able to use this tool.

Thanks!

**Comment by kennethwsmith** [comment]
See pull request #5 .  I was just thinking the same thing, so I did it... :)

**Comment by Redmega** [comment]
Closed by #5

**Comment by JohnnyQuazar** [comment]
Splendid! Thanks dudes
